# Generated by Django 2.1.5 on 2019-05-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tricycleowner',
            name='user',
        ),
        migrations.AddField(
            model_name='tricycleowner',
            name='fName',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tricycleowner',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tricycleowner',
            name='lName',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tricycleowner',
            name='lga_origin',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tricycleowner',
            name='oName',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tricycleowner',
            name='occupation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tricycleowner',
            name='phoneNumber',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tricycleowner',
            name='state_origin',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
