# Generated by Django 2.1.5 on 2019-05-07 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('napep', '0002_auto_20190507_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tricycle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='napep.Rider'),
        ),
    ]
